name: xdmcp-kiosk
version: git
summary: An Xorg server to run on Ubuntu Core allowing to display apps via XDMCP
description: |
  This snap will start an Xorg server on top of ubuntu-frame and allow you to display
  client appliications using XDMCP remotely on it.
  To allow access from remote hosts you need to supply a list of ip addresses that are
  permitted to show anything via the snap set command like
  .
      snap set xdmcp-kiosk hosts=192.168.1.10,192.168.1.20,192.168.1.30
  .
  Hosts in this list can then set the DISPLAY variable and spawn applications via XDMCP
  on the Ubuntu Core machine.
confinement: strict
compression: lzo
grade: stable
base: core24

apps:
  xdmcp-kiosk:
    command-chain: &_command-chain
      - bin/gpu-2404-wrapper
      - bin/wayland-launch
    command: &_command usr/bin/startx -- -retro -listen tcp
    plugs: &_plugs
      - hardware-observe
      - network
      - network-bind
      - opengl
      - wayland
    environment: &_environment
      XDG_DATA_HOME: $SNAP_DATA
      XDG_DATA_DIRS: $SNAP/usr/share

  daemon:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command-chain: *_command-chain
    command: *_command
    plugs: *_plugs
    environment: *_environment

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  x11-plug:
    interface: x11

slots:
  x11:

environment:
  XDG_CACHE_HOME:  $SNAP_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_DATA/.config
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_DATA_DIRS:   $SNAP/usr/local/share:$SNAP/usr/share
  # XKB config
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
  HOME: $SNAP_COMMON

layout:
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0
  /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gtk-3.0:
    bind: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gtk-3.0
  /usr/share/mime:
    bind: $SNAP/usr/share/mime
  /etc/gtk-3.0:
    bind: $SNAP/etc/gtk-3.0
  /usr/lib/xorg:
    bind: $SNAP/usr/lib/xorg
  /var/log:
    bind: $SNAP_COMMON/log
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /etc/X11:
    bind: $SNAP/etc/X11
  /usr/bin/X:
    symlink: $SNAP/usr/bin/X
  /usr/bin/Xorg:
    symlink: $SNAP/usr/bin/Xorg
  /usr/bin/mcookie:
    bind-file: $SNAP/usr/bin/mcookie

parts:
  x11:
    plugin: nil
    stage-packages:
      - libinput-bin
      - util-linux
      - xserver-xorg-core
      - xserver-xorg-input-libinput
      - x11-xserver-utils
      - xkb-data
      - xinit

  gsettings+pixbuf+immodules:
    plugin: nil
    build-packages:
      - libgdk-pixbuf2.0-0
      - librsvg2-common
      - shared-mime-info
      - libgtk-3-0
    override-build: |
      craftctl default
      update-mime-database ${CRAFT_PART_INSTALL}/usr/share/mime
      mkdir -p ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gtk-3.0/3.0.0/
      /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libgtk-3-0t64/gtk-query-immodules-3.0 > ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gtk-3.0/3.0.0/immodules.cache
    stage-packages:
      - librsvg2-common
      - gsettings-desktop-schemas
      - libglib2.0-bin
    override-prime: |
      craftctl default
      /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/glib-2.0/glib-compile-schemas "$CRAFT_PRIME/usr/share/glib-2.0/schemas"
      LOADERS_PATH=$(echo ${CRAFT_PRIME}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gdk-pixbuf-2.0/*/loaders)
      QUERY_LOADERS=/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_ON}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
      GDK_PIXBUF_MODULEDIR=${LOADERS_PATH} ${QUERY_LOADERS} > ${LOADERS_PATH}/../loaders.cache
      sed s!$CRAFT_PRIME!!g --in-place ${LOADERS_PATH}/../loaders.cache

  setup:
    plugin: dump
    source: wayland-launch
    override-build: |
      PLUGS="opengl wayland gpu-2404"
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/wayland-launch
      craftctl default
    stage-packages:
      - inotify-tools

  gpu-2404:
    after:
      - x11
      - gsettings+pixbuf+immodules
      - setup
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      cd "$CRAFT_PRIME/usr/share/"
      rm -rf bug drirc.d glvnd libdrm lintian man
      rm -rf applications apport bash-completion dbus-1 doc-base doc gtk-doc\
             help pkgconfig libthai metainfo themes thumbnailers xml
    prime:
      - bin/gpu-2404-wrapper

platforms:
  amd64:
  armhf:
  arm64:
