#! /bin/sh

cat << EOF >$SNAP_COMMON/.xinitrc
#! /bin/sh

xhost +localhost

echo "starting Xorg session \$(date)" >\$SNAP_COMMON/session.log

MYHOSTS="\$(snapctl get hosts)"
if [ -n \$MYHOSTS ]; then
    if \$(echo \$MYHOSTS|grep -q ,); then
      MYHOSTS="\$(echo \$MYHOSTS | tr ',' ' ')"
    fi
    for host in \$MYHOSTS; do
      echo "xhost +\$host" >>\$SNAP_COMMON/session.log
      xhost +\$host
    done
fi

xset s off
xset -dpms
xset s noblank

sleep infinity
EOF
